# Generated by Django 4.0.4 on 2022-05-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='uid',
        ),
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(default=1, upload_to='member'),
            preserve_default=False,
        ),
    ]
